"""Voice input and output adapters."""

from pokerbot_3000.voice.asr import (
    DEFAULT_ELEVENLABS_STT_LANGUAGE,
    DEFAULT_ELEVENLABS_STT_MODEL,
    ELEVENLABS_STT_LANGUAGE_ENV,
    ELEVENLABS_STT_MODEL_ENV,
    ElevenLabsSpeechTranscriber,
    ElevenLabsSpeechTranscriptionConfig,
)
from pokerbot_3000.voice.capture import (
    POKERBOT_VAD_MAX_PHRASE_MS_ENV,
    POKERBOT_VAD_MIN_PHRASE_MS_ENV,
    POKERBOT_VAD_RMS_THRESHOLD_ENV,
    POKERBOT_VAD_SILENCE_MS_ENV,
    POKERBOT_VOICE_DEVICE_ENV,
    BrowserAudioInput,
    EnergyVoiceActivityDetector,
    MicrophoneConfig,
    SoundDeviceAudioInput,
    VadConfig,
    VoiceRuntimeError,
)
from pokerbot_3000.voice.coordinator import VoiceActionAdapters, VoiceActionCoordinator, VoiceInputStatus
from pokerbot_3000.voice.elevenlabs import (
    ELEVENLABS_API_KEY_ENV,
    ELEVENLABS_ELIZA_SPEED_ENV,
    ELEVENLABS_ELIZA_VOICE_ID_ENV,
    ELEVENLABS_MODEL_ENV,
    ELEVENLABS_ORCHESTRATOR_SPEED_ENV,
    ELEVENLABS_ORCHESTRATOR_VOICE_ID_ENV,
    ELEVENLABS_REACHY_SPEED_ENV,
    ELEVENLABS_REACHY_VOICE_ID_ENV,
    ElevenLabsClient,
    ElevenLabsClientError,
    ElevenLabsConfig,
    ElevenLabsConfigurationError,
)
from pokerbot_3000.voice.grammar import DeterministicVoiceCommandParser

__all__ = [
    "DEFAULT_ELEVENLABS_STT_LANGUAGE",
    "DEFAULT_ELEVENLABS_STT_MODEL",
    "ELEVENLABS_API_KEY_ENV",
    "ELEVENLABS_ELIZA_SPEED_ENV",
    "ELEVENLABS_ELIZA_VOICE_ID_ENV",
    "ELEVENLABS_MODEL_ENV",
    "ELEVENLABS_ORCHESTRATOR_SPEED_ENV",
    "ELEVENLABS_ORCHESTRATOR_VOICE_ID_ENV",
    "ELEVENLABS_REACHY_SPEED_ENV",
    "ELEVENLABS_REACHY_VOICE_ID_ENV",
    "ELEVENLABS_STT_LANGUAGE_ENV",
    "ELEVENLABS_STT_MODEL_ENV",
    "POKERBOT_VAD_MAX_PHRASE_MS_ENV",
    "POKERBOT_VAD_MIN_PHRASE_MS_ENV",
    "POKERBOT_VAD_RMS_THRESHOLD_ENV",
    "POKERBOT_VAD_SILENCE_MS_ENV",
    "POKERBOT_VOICE_DEVICE_ENV",
    "BrowserAudioInput",
    "DeterministicVoiceCommandParser",
    "ElevenLabsClient",
    "ElevenLabsClientError",
    "ElevenLabsConfig",
    "ElevenLabsConfigurationError",
    "ElevenLabsSpeechTranscriber",
    "ElevenLabsSpeechTranscriptionConfig",
    "EnergyVoiceActivityDetector",
    "MicrophoneConfig",
    "SoundDeviceAudioInput",
    "VadConfig",
    "VoiceActionAdapters",
    "VoiceActionCoordinator",
    "VoiceInputStatus",
    "VoiceRuntimeError",
]
